### ISSUE TITLE
Counter component

### ISSUE THREAD

**Issue by SomewhatMay** [Arctos6135/Calvera#1]
A simple component that displays a counter with several ways of mutating the value.
Props:
- `Label: string`  The visible string beside the timer.
- `HasButtons: boolean`  Whether the component will display up and down buttons.
- `InitialValue: number | undefined`  Defaults to `0`.
- `Min: number | undefined`  Defaults to `Number.MIN_VALUE`
- `Max: number | undefined`  Defaults to `Number.MAX_VALUE`

Interface:
- Visible count
   - This should be editable by clicking on it
- Plus and minus buttons
- Should be inline

ex.
![image](https://github.com/Arctos6135/Kocab/assets/40745122/3326a982-ab18-4485-acb2-bba73107647d)

**Comment by BenM-BenM** [comment]
Since every input has a label, that goes under a separate type, so you dont need to include that in components

**Comment by SomewhatMay** [comment]
Implemented in 528195f
