### ISSUE TITLE
Clock component

### ISSUE THREAD

**Issue by SomewhatMay** [Arctos6135/Calvera#11]

**Comment by BenM-BenM** [comment]
What do you mean by this and what are we using it for?

**Comment by SomewhatMay** [comment]
This would be used for timing how long it takes for teams to hook on the chains.

**Comment by BenM-BenM** [comment]
Can we not just use a number?

**Comment by SomewhatMay** [comment]
I don't think it's very ergonomic, efficient, or accurate to have the scouter count the number of seconds in their head and put it on a counter.. it would be much easier if we had a timer.
