### ISSUE TITLE
Text box starts with 9/100 for the word limit

### ISSUE THREAD

**Issue by SomewhatMay** [Arctos6135/Calvera#27]
Not urgent, more QOL.

**Comment by BenM-BenM** [comment]
Yeah, I noticed this. Seems to be different but n different text boxes, but 9 is the most common one. We can work on a fix before windsor

**Comment by SomewhatMay** [comment]
Figured out while trying to sleep: the `Response` in the responses store is initiated as an empty object and as a result, the associated fields are initialized as undefined; this includes the textbox  values. The explicit string conversion in `Textbox.svelte` converts this undefined into `"undefined"` instead of `""`. However, since the value of the text input area is binded without any string conversion, it appears as empty, even though the content variable is set to `"undefined"`.
