### ISSUE TITLE
Checkbox component

### ISSUE THREAD

**Issue by BenM-BenM** [Arctos6135/Calvera#7]
I didn't know what to call this butits the yes or no box you can chec of thing.  

I've created a type for this in types.ts but someone still needs to code the actual component

`export type Checkbox = {`
`    type: "Checkbox",` This just lets us know what kind of component it is
`    id: string,` makes it unique from other checkboxes
`    initialValue?: boolean,` The default value.  Should default to false.  
`}`

**Comment by SomewhatMay** [comment]
Completed in e4cd759
